// src/lib/request-types.ts

export const HTTP_METHODS = ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

export const METHOD_COLOR: Record<HttpMethod, string> = {
  GET: "text-method-get",
  POST: "text-method-post",
  PUT: "text-method-put",
  DELETE: "text-method-delete",
  PATCH: "text-method-patch",
  HEAD: "text-method-head",
  OPTIONS: "text-method-options",
};

export interface KeyValue {
  id: string;
  key: string;
  value: string;
  description?: string;
  enabled: boolean;
  /** true when generated by the engine (Host, Content-Length, User-Agent…) */
  auto?: boolean;
  /** multipart: "text" | "file"; undefined for urlencoded/headers/params */
  type?: "text" | "file";
}

export type BodyMode = "json" | "form-urlencoded" | "form-multipart";

export interface RestBody {
  mode: BodyMode;
  json: string;
  form: KeyValue[]; // both urlencoded and multipart share; only multipart uses `type`
}

export type AuthType = "none" | "basic" | "bearer" | "apikey";

export type AuthConfig =
  | { type: "none" }
  | { type: "basic"; username: string; password: string }
  | { type: "bearer"; token: string }
  | { type: "apikey"; key: string; value: string; addTo: "header" | "query" };

export type RequestTab = "params" | "body" | "headers" | "auth";

export interface OpenRequest {
  id: string;
  name: string;
  method: HttpMethod;
  url: string;
  activeTab: RequestTab;
  params: KeyValue[];
  headers: KeyValue[];
  body: RestBody;
  auth: AuthConfig;
  /** collection-tree path to the request file (ids from root to the request) */
  path: string[];
  dirty: boolean;
}

export function makeEmptyRequest(
  id: string,
  name: string,
  method: HttpMethod = "GET",
  path: string[] = [],
): OpenRequest {
  return {
    id,
    name,
    method,
    url: "",
    activeTab: "params",
    params: [],
    headers: [],
    body: { mode: "json", json: "", form: [] },
    auth: { type: "none" },
    path,
    dirty: false,
  };
}
