// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCollections(workspaceId: string) : Promise<Result<CollectionNode[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_collections", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(workspaceId: string, name: string) : Promise<Result<CollectionNode, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { workspaceId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(workspaceId: string, parentPath: string[], name: string) : Promise<Result<CollectionNode, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { workspaceId, parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRequest(workspaceId: string, parentPath: string[], name: string, kind: RequestKind) : Promise<Result<CollectionNode, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_request", { workspaceId, parentPath, name, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameNode(workspaceId: string, path: string[], name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_node", { workspaceId, path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNode(workspaceId: string, path: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_node", { workspaceId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderChildren(workspaceId: string, parentPath: string[], orderedIds: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_children", { workspaceId, parentPath, orderedIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRequest(workspaceId: string, path: string[]) : Promise<Result<RequestFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_request", { workspaceId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRequest(workspaceId: string, path: string[], content: RequestContent) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_request", { workspaceId, path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendRequest(spec: SendSpec) : Promise<Result<HttpResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_request", { spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importWsdl(url: string) : Promise<Result<WsdlImportPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wsdl", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmWsdlImport(workspaceId: string, preview: WsdlImportPreview) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_wsdl_import", { workspaceId, preview }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOperationSchema(wsdlUrl: string, inputElement: QName) : Promise<Result<SchemaNode, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_operation_schema", { wsdlUrl, inputElement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendSoap(wsdlUrl: string, inputElement: QName, endpoint: string, soapAction: string, soapVersion: string, value: FormValue) : Promise<Result<HttpResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_soap", { wsdlUrl, inputElement, endpoint, soapAction, soapVersion, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Serialize the SOAP envelope from the current form value without sending it —
 * backs the request panel's XML preview. Pure: reuses the loaded schema, no I/O.
 */
async buildSoapEnvelope(schema: SchemaNode, soapAction: string, soapVersion: string, value: FormValue) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_soap_envelope", { schema, soapAction, soapVersion, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a raw SOAP envelope edited by hand in the XML view, bypassing the form
 * serializer. Transport metadata still follows the selected SOAP version.
 */
async sendSoapRaw(endpoint: string, envelope: string, soapAction: string, soapVersion: string) : Promise<Result<HttpResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_soap_raw", { endpoint, envelope, soapAction, soapVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a hand-edited envelope back into form values, guided by the schema.
 * Errors (non-conforming XML) tell the caller to keep the raw draft instead.
 */
async parseEnvelope(envelope: string, schema: SchemaNode) : Promise<Result<FormValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_envelope", { envelope, schema }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEnvironments(workspaceId: string) : Promise<Result<EnvironmentList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_environments", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveEnvironment(workspaceId: string, environment: Environment) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_environment", { workspaceId, environment }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEnvironment(workspaceId: string, id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_environment", { workspaceId, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Attribute = { name: string; xsdType: XsdType; required: boolean; enumValues: string[]; default: string | null }
export type AuthData = { type: "none" } | { type: "basic"; username: string; password: string } | { type: "bearer"; token: string } | { type: "apikey"; key: string; value: string; addTo: string }
export type BodyData = { mode: string; json: string; form: KeyValueEntry[] }
export type CollectionNode = { type: "folder"; id: string; name: string; children: CollectionNode[] } | ({ type: "request" } & RequestNode)
/**
 * A named set of variables. BTreeMap keeps TOML/JSON output sorted -> stable git diffs.
 */
export type Environment = { id: string; name: string; variables?: Partial<{ [key in string]: string }> }
export type EnvironmentList = { environments: Environment[]; 
/**
 * Per-file load failures ("file.toml: message") — corrupt files are
 * reported, never silently skipped (F2 spirit).
 */
errors: string[] }
/**
 * The instance the user filled in. Mirrors `NodeKind`; the serializer walks the
 * pair (SchemaNode, FormValue). See docs/domain-model.md §3.
 */
export type FormValue = { leaf: string | null } | { sequence: FormValue[] } | { choice: { branch: number; value: FormValue } } | { repeated: FormValue[] } | "nil" | "omitted" | { raw: string }
export type HttpResponse = { status: number; statusText: string; timeMs: number; sizeBytes: number; headers: Partial<{ [key in string]: string }>; body: string; timing: TimingBreakdown; fault: SoapFault | null }
export type KeyValueEntry = { id: string; key: string; value: string; description?: string | null; enabled: boolean; type?: string | null }
export type MaxOccurs = { bounded: number } | "unbounded"
export type NodeKind = { leaf: { xsdType: XsdType; enumValues: string[]; default: string | null; fixed: string | null } } | { sequence: SchemaNode[] } | { choice: SchemaNode[] } | "any"
export type Occurs = { min: number; max: MaxOccurs }
export type OperationRef = { name: string; endpoint: string; soapAction: string; soapVersion: SoapVersion; inputElement: QName }
export type QName = { namespace: string; local: string }
export type RequestContent = ({ kind: "rest"; method: string; url: string } | { kind: "soap"; wsdlUrl: string; operation: string; endpoint?: string | null; soapAction?: string | null; soapVersion?: string | null; inputElement?: QName | null }) & { params?: KeyValueEntry[]; headers?: KeyValueEntry[]; body?: BodyData | null; auth?: AuthData | null }
export type RequestFile = ({ kind: "rest"; method: string; url: string } | { kind: "soap"; wsdlUrl: string; operation: string; endpoint?: string | null; soapAction?: string | null; soapVersion?: string | null; inputElement?: QName | null }) & { id: string; name: string; params: KeyValueEntry[]; headers: KeyValueEntry[]; body?: BodyData | null; auth?: AuthData | null }
export type RequestKind = { kind: "rest"; method: string; url: string } | { kind: "soap"; wsdlUrl: string; operation: string; endpoint?: string | null; soapAction?: string | null; soapVersion?: string | null; inputElement?: QName | null }
export type RequestNode = ({ kind: "rest"; method: string; url: string } | { kind: "soap"; wsdlUrl: string; operation: string; endpoint?: string | null; soapAction?: string | null; soapVersion?: string | null; inputElement?: QName | null }) & { id: string; name: string }
/**
 * The shape of a SOAP operation input. Immutable tree derived from XSD.
 */
export type SchemaNode = { name: string; namespace: string | null; occurs: Occurs; nillable: boolean; doc: string | null; attributes: Attribute[]; kind: NodeKind }
export type SendSpec = { method: string; url: string; params?: KeyValueEntry[]; headers?: KeyValueEntry[]; body: BodyData; auth: AuthData }
export type SoapFault = { code: string; reason: string; detail: string | null; actor: string | null }
export type SoapVersion = "1.1" | "1.2"
/**
 * Per-phase timing of a single request (differentiator #3 — the waterfall).
 * MVP: one new connection per request, so every phase is always measured.
 */
export type TimingBreakdown = { dnsMs: number | null; tcpMs: number | null; tlsMs: number | null; ttfbMs: number; downloadMs: number; totalMs: number }
export type WsdlImportPreview = { serviceName: string; wsdlUrl: string; operations: OperationRef[] }
/**
 * Subset of simple types supported in MVP (ADR-010).
 */
export type XsdType = "string" | "boolean" | "integer" | "decimal" | "double" | "date" | "dateTime" | "time" | "gYearMonth" | "base64Binary" | { other: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
